// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDuhxXClHfeFDVSJRif-qWNcOEdRh5LI4Y',
    appId: '1:133381052742:web:3bab983da69f225e8c6d47',
    messagingSenderId: '133381052742',
    projectId: 'twokong-182bd',
    authDomain: 'twokong-182bd.firebaseapp.com',
    storageBucket: 'twokong-182bd.firebasestorage.app',
    measurementId: 'G-S58JFJVPD7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBKPZsgnIm_P6MkQE-FM7ZVIJeQu4nEU-M',
    appId: '1:133381052742:android:9806215715f29aab8c6d47',
    messagingSenderId: '133381052742',
    projectId: 'twokong-182bd',
    storageBucket: 'twokong-182bd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDb6_hKlHEomEKMfWLmo6XHobiTqc6DhaY',
    appId: '1:133381052742:ios:714ec88378295c778c6d47',
    messagingSenderId: '133381052742',
    projectId: 'twokong-182bd',
    storageBucket: 'twokong-182bd.firebasestorage.app',
    iosBundleId: 'com.example.twokong',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDb6_hKlHEomEKMfWLmo6XHobiTqc6DhaY',
    appId: '1:133381052742:ios:714ec88378295c778c6d47',
    messagingSenderId: '133381052742',
    projectId: 'twokong-182bd',
    storageBucket: 'twokong-182bd.firebasestorage.app',
    iosBundleId: 'com.example.twokong',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDuhxXClHfeFDVSJRif-qWNcOEdRh5LI4Y',
    appId: '1:133381052742:web:569f51a34a2875c88c6d47',
    messagingSenderId: '133381052742',
    projectId: 'twokong-182bd',
    authDomain: 'twokong-182bd.firebaseapp.com',
    storageBucket: 'twokong-182bd.firebasestorage.app',
    measurementId: 'G-CXTHRG1T1N',
  );
}
